blank_issues_enabled: true
contact_links:
  - name: "ðŸ’¬ Discussions"
    url: https://github.com/moeen-mahmud/remen/discussions
    about: Ask questions and share ideas
  - name: "ðŸ“– Documentation"
    url: https://github.com/moeen-mahmud/remen#readme
    about: Project README and docs
